/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPreviewRouteImport } from './routes/app-preview'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as DownloadMacosRouteImport } from './routes/download/macos'
import { Route as DownloadWindowsRouteImport } from './routes/download/windows'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as V1MeRouteImport } from './routes/v1/me'
import { Route as V1AuthLogoutRouteImport } from './routes/v1/auth/logout'
import { Route as V1AvatarsUserIdRouteImport } from './routes/v1/avatars/$userId'
import { Route as V1MeAvatarRouteImport } from './routes/v1/me/avatar'
import { Route as V1SkillsIndexRouteImport } from './routes/v1/skills/index'
import { Route as V1SkillsSkillIdRouteImport } from './routes/v1/skills/$skillId'
import { Route as V1SkillsMineRouteImport } from './routes/v1/skills/mine'
import { Route as V1TeamAuthRedeemRouteImport } from './routes/v1/team-auth/redeem'
import { Route as V1TeamAuthTicketRouteImport } from './routes/v1/team-auth/ticket'
import { Route as V1TeamHostsIceServersRouteImport } from './routes/v1/team-hosts/ice-servers'
import { Route as V1TeamInvitationsEmailRouteImport } from './routes/v1/team-invitations/email'
import { Route as V1TeamTunnelsProvisionRouteImport } from './routes/v1/team-tunnels/provision'
import { Route as V1AuthEmailStartRouteImport } from './routes/v1/auth/email/start'
import { Route as V1AuthEmailVerifyRouteImport } from './routes/v1/auth/email/verify'
import { Route as V1MarketplaceAgentsIndexRouteImport } from './routes/v1/marketplace/agents/index'
import { Route as V1MarketplaceAgentsAgentIdRouteImport } from './routes/v1/marketplace/agents/$agentId'
import { Route as V1MarketplaceAgentsMineRouteImport } from './routes/v1/marketplace/agents/mine'
import { Route as V1SkillsSkillIdContentRouteImport } from './routes/v1/skills/$skillId/content'
import { Route as V1SkillsSkillIdIconRouteImport } from './routes/v1/skills/$skillId/icon'
import { Route as V1SkillsSkillIdInstallRouteImport } from './routes/v1/skills/$skillId/install'
import { Route as V1SkillsAdminSubmissionsRouteImport } from './routes/v1/skills/admin/submissions'
import { Route as V1MarketplaceAgentsAgentIdAvatarRouteImport } from './routes/v1/marketplace/agents/$agentId/avatar'
import { Route as V1MarketplaceAgentsAgentIdInstallRouteImport } from './routes/v1/marketplace/agents/$agentId/install'
import { Route as V1MarketplaceAgentsAdminSubmissionsRouteImport } from './routes/v1/marketplace/agents/admin/submissions'
import { Route as V1SkillsSkillIdVersionsVersionIdRouteImport } from './routes/v1/skills/$skillId/versions/$versionId'
import { Route as V1SkillsAdminFeaturedSkillIdRouteImport } from './routes/v1/skills/admin/featured/$skillId'
import { Route as V1SkillsAdminSubmissionsVersionIdRouteImport } from './routes/v1/skills/admin/submissions/$versionId'
import { Route as V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport } from './routes/v1/marketplace/agents/admin/featured/$agentId'
import { Route as V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport } from './routes/v1/marketplace/agents/admin/submissions/$versionId'
import { Route as V1SkillsSkillIdVersionsVersionIdContentRouteImport } from './routes/v1/skills/$skillId/versions/$versionId/content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/app-preview',
  path: '/app-preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app-preview.lazy').then((d) => d.Route))
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DownloadMacosRoute = DownloadMacosRouteImport.update({
  id: '/download/macos',
  path: '/download/macos',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/download/windows',
  path: '/download/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeRoute = V1MeRouteImport.update({
  id: '/v1/me',
  path: '/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthLogoutRoute = V1AuthLogoutRouteImport.update({
  id: '/v1/auth/logout',
  path: '/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AvatarsUserIdRoute = V1AvatarsUserIdRouteImport.update({
  id: '/v1/avatars/$userId',
  path: '/v1/avatars/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeAvatarRoute = V1MeAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => V1MeRoute,
} as any)
const V1SkillsIndexRoute = V1SkillsIndexRouteImport.update({
  id: '/v1/skills/',
  path: '/v1/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsSkillIdRoute = V1SkillsSkillIdRouteImport.update({
  id: '/v1/skills/$skillId',
  path: '/v1/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsMineRoute = V1SkillsMineRouteImport.update({
  id: '/v1/skills/mine',
  path: '/v1/skills/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthRedeemRoute = V1TeamAuthRedeemRouteImport.update({
  id: '/v1/team-auth/redeem',
  path: '/v1/team-auth/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthTicketRoute = V1TeamAuthTicketRouteImport.update({
  id: '/v1/team-auth/ticket',
  path: '/v1/team-auth/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamHostsIceServersRoute = V1TeamHostsIceServersRouteImport.update({
  id: '/v1/team-hosts/ice-servers',
  path: '/v1/team-hosts/ice-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamInvitationsEmailRoute = V1TeamInvitationsEmailRouteImport.update({
  id: '/v1/team-invitations/email',
  path: '/v1/team-invitations/email',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamTunnelsProvisionRoute = V1TeamTunnelsProvisionRouteImport.update({
  id: '/v1/team-tunnels/provision',
  path: '/v1/team-tunnels/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailStartRoute = V1AuthEmailStartRouteImport.update({
  id: '/v1/auth/email/start',
  path: '/v1/auth/email/start',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailVerifyRoute = V1AuthEmailVerifyRouteImport.update({
  id: '/v1/auth/email/verify',
  path: '/v1/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MarketplaceAgentsIndexRoute =
  V1MarketplaceAgentsIndexRouteImport.update({
    id: '/v1/marketplace/agents/',
    path: '/v1/marketplace/agents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAgentIdRoute =
  V1MarketplaceAgentsAgentIdRouteImport.update({
    id: '/v1/marketplace/agents/$agentId',
    path: '/v1/marketplace/agents/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsMineRoute = V1MarketplaceAgentsMineRouteImport.update({
  id: '/v1/marketplace/agents/mine',
  path: '/v1/marketplace/agents/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsSkillIdContentRoute = V1SkillsSkillIdContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsSkillIdIconRoute = V1SkillsSkillIdIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsSkillIdInstallRoute = V1SkillsSkillIdInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsAdminSubmissionsRoute =
  V1SkillsAdminSubmissionsRouteImport.update({
    id: '/v1/skills/admin/submissions',
    path: '/v1/skills/admin/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAgentIdAvatarRoute =
  V1MarketplaceAgentsAgentIdAvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => V1MarketplaceAgentsAgentIdRoute,
  } as any)
const V1MarketplaceAgentsAgentIdInstallRoute =
  V1MarketplaceAgentsAgentIdInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => V1MarketplaceAgentsAgentIdRoute,
  } as any)
const V1MarketplaceAgentsAdminSubmissionsRoute =
  V1MarketplaceAgentsAdminSubmissionsRouteImport.update({
    id: '/v1/marketplace/agents/admin/submissions',
    path: '/v1/marketplace/agents/admin/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SkillsSkillIdVersionsVersionIdRoute =
  V1SkillsSkillIdVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => V1SkillsSkillIdRoute,
  } as any)
const V1SkillsAdminFeaturedSkillIdRoute =
  V1SkillsAdminFeaturedSkillIdRouteImport.update({
    id: '/v1/skills/admin/featured/$skillId',
    path: '/v1/skills/admin/featured/$skillId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SkillsAdminSubmissionsVersionIdRoute =
  V1SkillsAdminSubmissionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => V1SkillsAdminSubmissionsRoute,
  } as any)
const V1MarketplaceAgentsAdminFeaturedAgentIdRoute =
  V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport.update({
    id: '/v1/marketplace/agents/admin/featured/$agentId',
    path: '/v1/marketplace/agents/admin/featured/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAdminSubmissionsVersionIdRoute =
  V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => V1MarketplaceAgentsAdminSubmissionsRoute,
  } as any)
const V1SkillsSkillIdVersionsVersionIdContentRoute =
  V1SkillsSkillIdVersionsVersionIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => V1SkillsSkillIdVersionsVersionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/skills/': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v1/marketplace/agents/': typeof V1MarketplaceAgentsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/skills': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v1/marketplace/agents': typeof V1MarketplaceAgentsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/skills/': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v1/marketplace/agents/': typeof V1MarketplaceAgentsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/skills/'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v1/marketplace/agents/'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/skills'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v1/marketplace/agents'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
  id:
    | '__root__'
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/skills/'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v1/marketplace/agents/'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppPreviewRoute: typeof AppPreviewRoute
  JoinRoute: typeof JoinRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DownloadMacosRoute: typeof DownloadMacosRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  V1MeRoute: typeof V1MeRouteWithChildren
  V1AuthLogoutRoute: typeof V1AuthLogoutRoute
  V1AvatarsUserIdRoute: typeof V1AvatarsUserIdRoute
  V1SkillsSkillIdRoute: typeof V1SkillsSkillIdRouteWithChildren
  V1SkillsMineRoute: typeof V1SkillsMineRoute
  V1TeamAuthRedeemRoute: typeof V1TeamAuthRedeemRoute
  V1TeamAuthTicketRoute: typeof V1TeamAuthTicketRoute
  V1TeamHostsIceServersRoute: typeof V1TeamHostsIceServersRoute
  V1TeamInvitationsEmailRoute: typeof V1TeamInvitationsEmailRoute
  V1TeamTunnelsProvisionRoute: typeof V1TeamTunnelsProvisionRoute
  V1SkillsIndexRoute: typeof V1SkillsIndexRoute
  V1AuthEmailStartRoute: typeof V1AuthEmailStartRoute
  V1AuthEmailVerifyRoute: typeof V1AuthEmailVerifyRoute
  V1MarketplaceAgentsAgentIdRoute: typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  V1MarketplaceAgentsMineRoute: typeof V1MarketplaceAgentsMineRoute
  V1SkillsAdminSubmissionsRoute: typeof V1SkillsAdminSubmissionsRouteWithChildren
  V1MarketplaceAgentsIndexRoute: typeof V1MarketplaceAgentsIndexRoute
  V1MarketplaceAgentsAdminSubmissionsRoute: typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  V1SkillsAdminFeaturedSkillIdRoute: typeof V1SkillsAdminFeaturedSkillIdRoute
  V1MarketplaceAgentsAdminFeaturedAgentIdRoute: typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-preview': {
      id: '/app-preview'
      path: '/app-preview'
      fullPath: '/app-preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/macos': {
      id: '/download/macos'
      path: '/download/macos'
      fullPath: '/download/macos'
      preLoaderRoute: typeof DownloadMacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/download/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me': {
      id: '/v1/me'
      path: '/v1/me'
      fullPath: '/v1/me'
      preLoaderRoute: typeof V1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/logout': {
      id: '/v1/auth/logout'
      path: '/v1/auth/logout'
      fullPath: '/v1/auth/logout'
      preLoaderRoute: typeof V1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/avatars/$userId': {
      id: '/v1/avatars/$userId'
      path: '/v1/avatars/$userId'
      fullPath: '/v1/avatars/$userId'
      preLoaderRoute: typeof V1AvatarsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me/avatar': {
      id: '/v1/me/avatar'
      path: '/avatar'
      fullPath: '/v1/me/avatar'
      preLoaderRoute: typeof V1MeAvatarRouteImport
      parentRoute: typeof V1MeRoute
    }
    '/v1/skills/': {
      id: '/v1/skills/'
      path: '/v1/skills'
      fullPath: '/v1/skills/'
      preLoaderRoute: typeof V1SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/$skillId': {
      id: '/v1/skills/$skillId'
      path: '/v1/skills/$skillId'
      fullPath: '/v1/skills/$skillId'
      preLoaderRoute: typeof V1SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/mine': {
      id: '/v1/skills/mine'
      path: '/v1/skills/mine'
      fullPath: '/v1/skills/mine'
      preLoaderRoute: typeof V1SkillsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/redeem': {
      id: '/v1/team-auth/redeem'
      path: '/v1/team-auth/redeem'
      fullPath: '/v1/team-auth/redeem'
      preLoaderRoute: typeof V1TeamAuthRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/ticket': {
      id: '/v1/team-auth/ticket'
      path: '/v1/team-auth/ticket'
      fullPath: '/v1/team-auth/ticket'
      preLoaderRoute: typeof V1TeamAuthTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-hosts/ice-servers': {
      id: '/v1/team-hosts/ice-servers'
      path: '/v1/team-hosts/ice-servers'
      fullPath: '/v1/team-hosts/ice-servers'
      preLoaderRoute: typeof V1TeamHostsIceServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-invitations/email': {
      id: '/v1/team-invitations/email'
      path: '/v1/team-invitations/email'
      fullPath: '/v1/team-invitations/email'
      preLoaderRoute: typeof V1TeamInvitationsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-tunnels/provision': {
      id: '/v1/team-tunnels/provision'
      path: '/v1/team-tunnels/provision'
      fullPath: '/v1/team-tunnels/provision'
      preLoaderRoute: typeof V1TeamTunnelsProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/start': {
      id: '/v1/auth/email/start'
      path: '/v1/auth/email/start'
      fullPath: '/v1/auth/email/start'
      preLoaderRoute: typeof V1AuthEmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/verify': {
      id: '/v1/auth/email/verify'
      path: '/v1/auth/email/verify'
      fullPath: '/v1/auth/email/verify'
      preLoaderRoute: typeof V1AuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/': {
      id: '/v1/marketplace/agents/'
      path: '/v1/marketplace/agents'
      fullPath: '/v1/marketplace/agents/'
      preLoaderRoute: typeof V1MarketplaceAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/$agentId': {
      id: '/v1/marketplace/agents/$agentId'
      path: '/v1/marketplace/agents/$agentId'
      fullPath: '/v1/marketplace/agents/$agentId'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/mine': {
      id: '/v1/marketplace/agents/mine'
      path: '/v1/marketplace/agents/mine'
      fullPath: '/v1/marketplace/agents/mine'
      preLoaderRoute: typeof V1MarketplaceAgentsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/$skillId/content': {
      id: '/v1/skills/$skillId/content'
      path: '/content'
      fullPath: '/v1/skills/$skillId/content'
      preLoaderRoute: typeof V1SkillsSkillIdContentRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/$skillId/icon': {
      id: '/v1/skills/$skillId/icon'
      path: '/icon'
      fullPath: '/v1/skills/$skillId/icon'
      preLoaderRoute: typeof V1SkillsSkillIdIconRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/$skillId/install': {
      id: '/v1/skills/$skillId/install'
      path: '/install'
      fullPath: '/v1/skills/$skillId/install'
      preLoaderRoute: typeof V1SkillsSkillIdInstallRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/admin/submissions': {
      id: '/v1/skills/admin/submissions'
      path: '/v1/skills/admin/submissions'
      fullPath: '/v1/skills/admin/submissions'
      preLoaderRoute: typeof V1SkillsAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/$agentId/avatar': {
      id: '/v1/marketplace/agents/$agentId/avatar'
      path: '/avatar'
      fullPath: '/v1/marketplace/agents/$agentId/avatar'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdAvatarRouteImport
      parentRoute: typeof V1MarketplaceAgentsAgentIdRoute
    }
    '/v1/marketplace/agents/$agentId/install': {
      id: '/v1/marketplace/agents/$agentId/install'
      path: '/install'
      fullPath: '/v1/marketplace/agents/$agentId/install'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdInstallRouteImport
      parentRoute: typeof V1MarketplaceAgentsAgentIdRoute
    }
    '/v1/marketplace/agents/admin/submissions': {
      id: '/v1/marketplace/agents/admin/submissions'
      path: '/v1/marketplace/agents/admin/submissions'
      fullPath: '/v1/marketplace/agents/admin/submissions'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/$skillId/versions/$versionId': {
      id: '/v1/skills/$skillId/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/v1/skills/$skillId/versions/$versionId'
      preLoaderRoute: typeof V1SkillsSkillIdVersionsVersionIdRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/admin/featured/$skillId': {
      id: '/v1/skills/admin/featured/$skillId'
      path: '/v1/skills/admin/featured/$skillId'
      fullPath: '/v1/skills/admin/featured/$skillId'
      preLoaderRoute: typeof V1SkillsAdminFeaturedSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/admin/submissions/$versionId': {
      id: '/v1/skills/admin/submissions/$versionId'
      path: '/$versionId'
      fullPath: '/v1/skills/admin/submissions/$versionId'
      preLoaderRoute: typeof V1SkillsAdminSubmissionsVersionIdRouteImport
      parentRoute: typeof V1SkillsAdminSubmissionsRoute
    }
    '/v1/marketplace/agents/admin/featured/$agentId': {
      id: '/v1/marketplace/agents/admin/featured/$agentId'
      path: '/v1/marketplace/agents/admin/featured/$agentId'
      fullPath: '/v1/marketplace/agents/admin/featured/$agentId'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/admin/submissions/$versionId': {
      id: '/v1/marketplace/agents/admin/submissions/$versionId'
      path: '/$versionId'
      fullPath: '/v1/marketplace/agents/admin/submissions/$versionId'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport
      parentRoute: typeof V1MarketplaceAgentsAdminSubmissionsRoute
    }
    '/v1/skills/$skillId/versions/$versionId/content': {
      id: '/v1/skills/$skillId/versions/$versionId/content'
      path: '/content'
      fullPath: '/v1/skills/$skillId/versions/$versionId/content'
      preLoaderRoute: typeof V1SkillsSkillIdVersionsVersionIdContentRouteImport
      parentRoute: typeof V1SkillsSkillIdVersionsVersionIdRoute
    }
  }
}

interface V1MeRouteChildren {
  V1MeAvatarRoute: typeof V1MeAvatarRoute
}

const V1MeRouteChildren: V1MeRouteChildren = {
  V1MeAvatarRoute: V1MeAvatarRoute,
}

const V1MeRouteWithChildren = V1MeRoute._addFileChildren(V1MeRouteChildren)

interface V1SkillsSkillIdVersionsVersionIdRouteChildren {
  V1SkillsSkillIdVersionsVersionIdContentRoute: typeof V1SkillsSkillIdVersionsVersionIdContentRoute
}

const V1SkillsSkillIdVersionsVersionIdRouteChildren: V1SkillsSkillIdVersionsVersionIdRouteChildren =
  {
    V1SkillsSkillIdVersionsVersionIdContentRoute:
      V1SkillsSkillIdVersionsVersionIdContentRoute,
  }

const V1SkillsSkillIdVersionsVersionIdRouteWithChildren =
  V1SkillsSkillIdVersionsVersionIdRoute._addFileChildren(
    V1SkillsSkillIdVersionsVersionIdRouteChildren,
  )

interface V1SkillsSkillIdRouteChildren {
  V1SkillsSkillIdContentRoute: typeof V1SkillsSkillIdContentRoute
  V1SkillsSkillIdIconRoute: typeof V1SkillsSkillIdIconRoute
  V1SkillsSkillIdInstallRoute: typeof V1SkillsSkillIdInstallRoute
  V1SkillsSkillIdVersionsVersionIdRoute: typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
}

const V1SkillsSkillIdRouteChildren: V1SkillsSkillIdRouteChildren = {
  V1SkillsSkillIdContentRoute: V1SkillsSkillIdContentRoute,
  V1SkillsSkillIdIconRoute: V1SkillsSkillIdIconRoute,
  V1SkillsSkillIdInstallRoute: V1SkillsSkillIdInstallRoute,
  V1SkillsSkillIdVersionsVersionIdRoute:
    V1SkillsSkillIdVersionsVersionIdRouteWithChildren,
}

const V1SkillsSkillIdRouteWithChildren = V1SkillsSkillIdRoute._addFileChildren(
  V1SkillsSkillIdRouteChildren,
)

interface V1MarketplaceAgentsAgentIdRouteChildren {
  V1MarketplaceAgentsAgentIdAvatarRoute: typeof V1MarketplaceAgentsAgentIdAvatarRoute
  V1MarketplaceAgentsAgentIdInstallRoute: typeof V1MarketplaceAgentsAgentIdInstallRoute
}

const V1MarketplaceAgentsAgentIdRouteChildren: V1MarketplaceAgentsAgentIdRouteChildren =
  {
    V1MarketplaceAgentsAgentIdAvatarRoute:
      V1MarketplaceAgentsAgentIdAvatarRoute,
    V1MarketplaceAgentsAgentIdInstallRoute:
      V1MarketplaceAgentsAgentIdInstallRoute,
  }

const V1MarketplaceAgentsAgentIdRouteWithChildren =
  V1MarketplaceAgentsAgentIdRoute._addFileChildren(
    V1MarketplaceAgentsAgentIdRouteChildren,
  )

interface V1SkillsAdminSubmissionsRouteChildren {
  V1SkillsAdminSubmissionsVersionIdRoute: typeof V1SkillsAdminSubmissionsVersionIdRoute
}

const V1SkillsAdminSubmissionsRouteChildren: V1SkillsAdminSubmissionsRouteChildren =
  {
    V1SkillsAdminSubmissionsVersionIdRoute:
      V1SkillsAdminSubmissionsVersionIdRoute,
  }

const V1SkillsAdminSubmissionsRouteWithChildren =
  V1SkillsAdminSubmissionsRoute._addFileChildren(
    V1SkillsAdminSubmissionsRouteChildren,
  )

interface V1MarketplaceAgentsAdminSubmissionsRouteChildren {
  V1MarketplaceAgentsAdminSubmissionsVersionIdRoute: typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
}

const V1MarketplaceAgentsAdminSubmissionsRouteChildren: V1MarketplaceAgentsAdminSubmissionsRouteChildren =
  {
    V1MarketplaceAgentsAdminSubmissionsVersionIdRoute:
      V1MarketplaceAgentsAdminSubmissionsVersionIdRoute,
  }

const V1MarketplaceAgentsAdminSubmissionsRouteWithChildren =
  V1MarketplaceAgentsAdminSubmissionsRoute._addFileChildren(
    V1MarketplaceAgentsAdminSubmissionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppPreviewRoute: AppPreviewRoute,
  JoinRoute: JoinRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  V1MeRoute: V1MeRouteWithChildren,
  V1AuthLogoutRoute: V1AuthLogoutRoute,
  V1AvatarsUserIdRoute: V1AvatarsUserIdRoute,
  V1SkillsSkillIdRoute: V1SkillsSkillIdRouteWithChildren,
  V1SkillsMineRoute: V1SkillsMineRoute,
  V1TeamAuthRedeemRoute: V1TeamAuthRedeemRoute,
  V1TeamAuthTicketRoute: V1TeamAuthTicketRoute,
  V1TeamHostsIceServersRoute: V1TeamHostsIceServersRoute,
  V1TeamInvitationsEmailRoute: V1TeamInvitationsEmailRoute,
  V1TeamTunnelsProvisionRoute: V1TeamTunnelsProvisionRoute,
  V1SkillsIndexRoute: V1SkillsIndexRoute,
  V1AuthEmailStartRoute: V1AuthEmailStartRoute,
  V1AuthEmailVerifyRoute: V1AuthEmailVerifyRoute,
  V1MarketplaceAgentsAgentIdRoute: V1MarketplaceAgentsAgentIdRouteWithChildren,
  V1MarketplaceAgentsMineRoute: V1MarketplaceAgentsMineRoute,
  V1SkillsAdminSubmissionsRoute: V1SkillsAdminSubmissionsRouteWithChildren,
  V1MarketplaceAgentsIndexRoute: V1MarketplaceAgentsIndexRoute,
  V1MarketplaceAgentsAdminSubmissionsRoute:
    V1MarketplaceAgentsAdminSubmissionsRouteWithChildren,
  V1SkillsAdminFeaturedSkillIdRoute: V1SkillsAdminFeaturedSkillIdRoute,
  V1MarketplaceAgentsAdminFeaturedAgentIdRoute:
    V1MarketplaceAgentsAdminFeaturedAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
