/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as V1MeRouteImport } from './routes/v1/me'
import { Route as V1AuthLogoutRouteImport } from './routes/v1/auth/logout'
import { Route as V1TeamAuthRedeemRouteImport } from './routes/v1/team-auth/redeem'
import { Route as V1TeamAuthTicketRouteImport } from './routes/v1/team-auth/ticket'
import { Route as V1TeamInvitationsEmailRouteImport } from './routes/v1/team-invitations/email'
import { Route as V1AuthEmailStartRouteImport } from './routes/v1/auth/email/start'
import { Route as V1AuthEmailVerifyRouteImport } from './routes/v1/auth/email/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeRoute = V1MeRouteImport.update({
  id: '/v1/me',
  path: '/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthLogoutRoute = V1AuthLogoutRouteImport.update({
  id: '/v1/auth/logout',
  path: '/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthRedeemRoute = V1TeamAuthRedeemRouteImport.update({
  id: '/v1/team-auth/redeem',
  path: '/v1/team-auth/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthTicketRoute = V1TeamAuthTicketRouteImport.update({
  id: '/v1/team-auth/ticket',
  path: '/v1/team-auth/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamInvitationsEmailRoute = V1TeamInvitationsEmailRouteImport.update({
  id: '/v1/team-invitations/email',
  path: '/v1/team-invitations/email',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailStartRoute = V1AuthEmailStartRouteImport.update({
  id: '/v1/auth/email/start',
  path: '/v1/auth/email/start',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailVerifyRoute = V1AuthEmailVerifyRouteImport.update({
  id: '/v1/auth/email/verify',
  path: '/v1/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-invitations/email'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-invitations/email'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  id:
    | '__root__'
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-invitations/email'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  V1MeRoute: typeof V1MeRoute
  V1AuthLogoutRoute: typeof V1AuthLogoutRoute
  V1TeamAuthRedeemRoute: typeof V1TeamAuthRedeemRoute
  V1TeamAuthTicketRoute: typeof V1TeamAuthTicketRoute
  V1TeamInvitationsEmailRoute: typeof V1TeamInvitationsEmailRoute
  V1AuthEmailStartRoute: typeof V1AuthEmailStartRoute
  V1AuthEmailVerifyRoute: typeof V1AuthEmailVerifyRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me': {
      id: '/v1/me'
      path: '/v1/me'
      fullPath: '/v1/me'
      preLoaderRoute: typeof V1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/logout': {
      id: '/v1/auth/logout'
      path: '/v1/auth/logout'
      fullPath: '/v1/auth/logout'
      preLoaderRoute: typeof V1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/redeem': {
      id: '/v1/team-auth/redeem'
      path: '/v1/team-auth/redeem'
      fullPath: '/v1/team-auth/redeem'
      preLoaderRoute: typeof V1TeamAuthRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/ticket': {
      id: '/v1/team-auth/ticket'
      path: '/v1/team-auth/ticket'
      fullPath: '/v1/team-auth/ticket'
      preLoaderRoute: typeof V1TeamAuthTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-invitations/email': {
      id: '/v1/team-invitations/email'
      path: '/v1/team-invitations/email'
      fullPath: '/v1/team-invitations/email'
      preLoaderRoute: typeof V1TeamInvitationsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/start': {
      id: '/v1/auth/email/start'
      path: '/v1/auth/email/start'
      fullPath: '/v1/auth/email/start'
      preLoaderRoute: typeof V1AuthEmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/verify': {
      id: '/v1/auth/email/verify'
      path: '/v1/auth/email/verify'
      fullPath: '/v1/auth/email/verify'
      preLoaderRoute: typeof V1AuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  V1MeRoute: V1MeRoute,
  V1AuthLogoutRoute: V1AuthLogoutRoute,
  V1TeamAuthRedeemRoute: V1TeamAuthRedeemRoute,
  V1TeamAuthTicketRoute: V1TeamAuthTicketRoute,
  V1TeamInvitationsEmailRoute: V1TeamInvitationsEmailRoute,
  V1AuthEmailStartRoute: V1AuthEmailStartRoute,
  V1AuthEmailVerifyRoute: V1AuthEmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
