/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPreviewRouteImport } from './routes/app-preview'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as DownloadMacosRouteImport } from './routes/download/macos'
import { Route as DownloadWindowsRouteImport } from './routes/download/windows'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as V1MeRouteImport } from './routes/v1/me'
import { Route as V1AuthLogoutRouteImport } from './routes/v1/auth/logout'
import { Route as V1AvatarsUserIdRouteImport } from './routes/v1/avatars/$userId'
import { Route as V1MeAvatarRouteImport } from './routes/v1/me/avatar'
import { Route as V1TeamAuthRedeemRouteImport } from './routes/v1/team-auth/redeem'
import { Route as V1TeamAuthTicketRouteImport } from './routes/v1/team-auth/ticket'
import { Route as V1TeamHostsIceServersRouteImport } from './routes/v1/team-hosts/ice-servers'
import { Route as V1TeamInvitationsEmailRouteImport } from './routes/v1/team-invitations/email'
import { Route as V1TeamTunnelsProvisionRouteImport } from './routes/v1/team-tunnels/provision'
import { Route as V1AuthEmailStartRouteImport } from './routes/v1/auth/email/start'
import { Route as V1AuthEmailVerifyRouteImport } from './routes/v1/auth/email/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/app-preview',
  path: '/app-preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app-preview.lazy').then((d) => d.Route))
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DownloadMacosRoute = DownloadMacosRouteImport.update({
  id: '/download/macos',
  path: '/download/macos',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/download/windows',
  path: '/download/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeRoute = V1MeRouteImport.update({
  id: '/v1/me',
  path: '/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthLogoutRoute = V1AuthLogoutRouteImport.update({
  id: '/v1/auth/logout',
  path: '/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AvatarsUserIdRoute = V1AvatarsUserIdRouteImport.update({
  id: '/v1/avatars/$userId',
  path: '/v1/avatars/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeAvatarRoute = V1MeAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => V1MeRoute,
} as any)
const V1TeamAuthRedeemRoute = V1TeamAuthRedeemRouteImport.update({
  id: '/v1/team-auth/redeem',
  path: '/v1/team-auth/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthTicketRoute = V1TeamAuthTicketRouteImport.update({
  id: '/v1/team-auth/ticket',
  path: '/v1/team-auth/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamHostsIceServersRoute = V1TeamHostsIceServersRouteImport.update({
  id: '/v1/team-hosts/ice-servers',
  path: '/v1/team-hosts/ice-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamInvitationsEmailRoute = V1TeamInvitationsEmailRouteImport.update({
  id: '/v1/team-invitations/email',
  path: '/v1/team-invitations/email',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamTunnelsProvisionRoute = V1TeamTunnelsProvisionRouteImport.update({
  id: '/v1/team-tunnels/provision',
  path: '/v1/team-tunnels/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailStartRoute = V1AuthEmailStartRouteImport.update({
  id: '/v1/auth/email/start',
  path: '/v1/auth/email/start',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailVerifyRoute = V1AuthEmailVerifyRouteImport.update({
  id: '/v1/auth/email/verify',
  path: '/v1/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  id:
    | '__root__'
    | '/'
    | '/app-preview'
    | '/join'
    | '/.well-known/apple-app-site-association'
    | '/download/macos'
    | '/download/windows'
    | '/health/live'
    | '/health/ready'
    | '/v1/me'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppPreviewRoute: typeof AppPreviewRoute
  JoinRoute: typeof JoinRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DownloadMacosRoute: typeof DownloadMacosRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  V1MeRoute: typeof V1MeRouteWithChildren
  V1AuthLogoutRoute: typeof V1AuthLogoutRoute
  V1AvatarsUserIdRoute: typeof V1AvatarsUserIdRoute
  V1TeamAuthRedeemRoute: typeof V1TeamAuthRedeemRoute
  V1TeamAuthTicketRoute: typeof V1TeamAuthTicketRoute
  V1TeamHostsIceServersRoute: typeof V1TeamHostsIceServersRoute
  V1TeamInvitationsEmailRoute: typeof V1TeamInvitationsEmailRoute
  V1TeamTunnelsProvisionRoute: typeof V1TeamTunnelsProvisionRoute
  V1AuthEmailStartRoute: typeof V1AuthEmailStartRoute
  V1AuthEmailVerifyRoute: typeof V1AuthEmailVerifyRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-preview': {
      id: '/app-preview'
      path: '/app-preview'
      fullPath: '/app-preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/macos': {
      id: '/download/macos'
      path: '/download/macos'
      fullPath: '/download/macos'
      preLoaderRoute: typeof DownloadMacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/download/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me': {
      id: '/v1/me'
      path: '/v1/me'
      fullPath: '/v1/me'
      preLoaderRoute: typeof V1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/logout': {
      id: '/v1/auth/logout'
      path: '/v1/auth/logout'
      fullPath: '/v1/auth/logout'
      preLoaderRoute: typeof V1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/avatars/$userId': {
      id: '/v1/avatars/$userId'
      path: '/v1/avatars/$userId'
      fullPath: '/v1/avatars/$userId'
      preLoaderRoute: typeof V1AvatarsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me/avatar': {
      id: '/v1/me/avatar'
      path: '/avatar'
      fullPath: '/v1/me/avatar'
      preLoaderRoute: typeof V1MeAvatarRouteImport
      parentRoute: typeof V1MeRoute
    }
    '/v1/team-auth/redeem': {
      id: '/v1/team-auth/redeem'
      path: '/v1/team-auth/redeem'
      fullPath: '/v1/team-auth/redeem'
      preLoaderRoute: typeof V1TeamAuthRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/ticket': {
      id: '/v1/team-auth/ticket'
      path: '/v1/team-auth/ticket'
      fullPath: '/v1/team-auth/ticket'
      preLoaderRoute: typeof V1TeamAuthTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-hosts/ice-servers': {
      id: '/v1/team-hosts/ice-servers'
      path: '/v1/team-hosts/ice-servers'
      fullPath: '/v1/team-hosts/ice-servers'
      preLoaderRoute: typeof V1TeamHostsIceServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-invitations/email': {
      id: '/v1/team-invitations/email'
      path: '/v1/team-invitations/email'
      fullPath: '/v1/team-invitations/email'
      preLoaderRoute: typeof V1TeamInvitationsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-tunnels/provision': {
      id: '/v1/team-tunnels/provision'
      path: '/v1/team-tunnels/provision'
      fullPath: '/v1/team-tunnels/provision'
      preLoaderRoute: typeof V1TeamTunnelsProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/start': {
      id: '/v1/auth/email/start'
      path: '/v1/auth/email/start'
      fullPath: '/v1/auth/email/start'
      preLoaderRoute: typeof V1AuthEmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/verify': {
      id: '/v1/auth/email/verify'
      path: '/v1/auth/email/verify'
      fullPath: '/v1/auth/email/verify'
      preLoaderRoute: typeof V1AuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface V1MeRouteChildren {
  V1MeAvatarRoute: typeof V1MeAvatarRoute
}

const V1MeRouteChildren: V1MeRouteChildren = {
  V1MeAvatarRoute: V1MeAvatarRoute,
}

const V1MeRouteWithChildren = V1MeRoute._addFileChildren(V1MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppPreviewRoute: AppPreviewRoute,
  JoinRoute: JoinRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  V1MeRoute: V1MeRouteWithChildren,
  V1AuthLogoutRoute: V1AuthLogoutRoute,
  V1AvatarsUserIdRoute: V1AvatarsUserIdRoute,
  V1TeamAuthRedeemRoute: V1TeamAuthRedeemRoute,
  V1TeamAuthTicketRoute: V1TeamAuthTicketRoute,
  V1TeamHostsIceServersRoute: V1TeamHostsIceServersRoute,
  V1TeamInvitationsEmailRoute: V1TeamInvitationsEmailRoute,
  V1TeamTunnelsProvisionRoute: V1TeamTunnelsProvisionRoute,
  V1AuthEmailStartRoute: V1AuthEmailStartRoute,
  V1AuthEmailVerifyRoute: V1AuthEmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
